### PR TITLE
fixes build problems

### LINKED ISSUE #32: build problems
I installed coyaml separately but the build fails of zerogw

```
raise Errors.WafError('No wscript file in directory %s'%d)
```

waflib.Errors.WafError: No wscript file in directory /mnt/data/home/mdupont/experiments/zerogw/coyaml

this dir is empty :
zerogw/coyaml

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
update readme about subdirs
fix missing include

### CODE REVIEW

**Comment by h4ck3rm1k3** [comment]
see #32

**Comment by tailhook** [comment]
Well, you probably just need to do `git submodule update --init` instead of symlinks. This is how git submodules work.

**Comment by h4ck3rm1k3** [comment]
Well I don't see that in the instructions. If I install the modules why cannot it find them? This is not normal behavior that I am used to with make, automake, cmake pkgconfig etc.

**Comment by h4ck3rm1k3** [comment]
Ok updated readme.

**Comment by h4ck3rm1k3** [comment]
closing because of no feedback. I have continued with my branch and now have a first version compiled for netbsd 6.1.5 and zmq 3. Will be testing it now. If you are interested in pull requests for this let me know.

**Pull request closed without merging**
